set(CMAKE_SYSTEM_NAME Haiku)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(HAIKU_TOOLCHAIN_DIR /tools/cross-tools-x86_64)
set(HAIKU_TARGET x86_64-unknown-haiku)

set(CMAKE_C_COMPILER   ${HAIKU_TOOLCHAIN_DIR}/bin/${HAIKU_TARGET}-gcc)
set(CMAKE_CXX_COMPILER ${HAIKU_TOOLCHAIN_DIR}/bin/${HAIKU_TARGET}-g++)
set(CMAKE_AR            ${HAIKU_TOOLCHAIN_DIR}/bin/${HAIKU_TARGET}-ar     CACHE FILEPATH "")
set(CMAKE_RANLIB        ${HAIKU_TOOLCHAIN_DIR}/bin/${HAIKU_TARGET}-ranlib CACHE FILEPATH "")

set(CMAKE_FIND_ROOT_PATH /system)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)