plugins {
    id 'com.android.application'
}

def keystorePropertiesFile = rootProject.file("./keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "org.noentertainment.sbsidequest"
    compileSdk = 35

    defaultConfig {
        applicationId 'org.noentertainment.sbsidequest'
        minSdk = 21
        targetSdk = 35
        versionCode 1
        versionName '1.0'

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared', '-DDOWNLOAD_DEPENDENCIES=OFF'
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
                // abiFilters 'arm64-v8a'
            }
        }
    }

    sourceSets.main {
        assets.srcDirs = ['../../build/build-files/include-files']
        
        java.srcDirs = ['../../code/3rdparty/SDL/android-project/app/src/main/java']
        res.srcDirs = ['../../code/3rdparty/SDL/android-project/app/src/main/res']
    }

    externalNativeBuild {
        cmake {
            path '../../CMakeLists.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        prefab = true
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
}


/* tasks.register('prepareResources', Exec) {
    workingDir "$projectDir/../.."
    commandLine 'bash', 'build/prepare-resources.sh'
}

tasks.named('preBuild') {
    dependsOn tasks.named('prepareResources')
}
*/