#pragma once

#include <SDL3/SDL.h>

#if SDL_PLATFORM_PSP
#define PLATFORM_DEVCONSOLE_MAX_LINES 50

#elif SDL_PLATFORM_ANDROID
#define PLATFORM_HAS_TOUCH

#else
#define PLATFORM_HAS_KEYBOARD
#define PLATFORM_HAS_MOUSE
#define PLATFORM_HAS_RIGHT_JOY
#define PLATFORM_HAS_TRIGGERS
#define PLATFORM_DEVCONSOLE_MAX_LINES 500

#endif