#pragma once

#include <SDL3/SDL.h>

#define PLATFORM_HAS_KEYBOARD
#define PLATFORM_HAS_MOUSE
#define PLATFORM_HAS_RIGHT_JOY
#define PLATFORM_HAS_TRIGGERS
#define PLATFORM_DEVCONSOLE_MAX_LINES 500
#define PLATFORM_HAS_STRING_COMMANDS
#define PLATFORM_HAS_FILE_EXPLORER
#define PLATFORM_HAS_FILE_PICKER
#define PLATFORM_HAS_FOLDER_PICKER
#define PLATFORM_INITIAL_RES 960, 540
#define PLATFORM_WINDOW_FLAGS SDL_WINDOW_RESIZABLE

#if SDL_PLATFORM_PSP
#undef PLATFORM_DEVCONSOLE_MAX_LINES
#define PLATFORM_DEVCONSOLE_MAX_LINES 50
#undef PLATFORM_INITIAL_RES
#define PLATFORM_INITIAL_RES 480, 272
#undef PLATFORM_HAS_KEYBOARD
#undef PLATFORM_HAS_MOUSE
#undef PLATFORM_HAS_RIGHT_JOY
#undef PLATFORM_HAS_TRIGGERS
#undef PLATFORM_HAS_STRING_COMMANDS
#undef PLATFORM_HAS_FILE_PICKER
#undef PLATFORM_HAS_FILE_EXPLORER

#elif SDL_PLATFORM_PS2
#undef PLATFORM_DEVCONSOLE_MAX_LINES
#define PLATFORM_DEVCONSOLE_MAX_LINES 50
#undef PLATFORM_INITIAL_RES
#define PLATFORM_INITIAL_RES 240, 135
// ps2 does have a keyboard and mouse but not sure if they work

#elif SDL_PLATFORM_ANDROID
#undef PLATFORM_WINDOW_FLAGS
#define PLATFORM_WINDOW_FLAGS SDL_WINDOW_RESIZEABLE | SDL_WINDOW_FULLSCREEN
#define PLATFORM_HAS_TOUCH
#define PLATFORM_TOUCH_BY_DEFAULT
#undef PLATFORM_HAS_FOLDER_PICKER
#undef PLATFORM_HAS_FILE_EXPLORER

#elif SDL_PLATFORM_EMSCRIPTEN
#define PLATFORM_HAS_TOUCH
#undef PLATFORM_HAS_FOLDER_PICKER
#undef PLATFORM_HAS_FILE_EXPLORER

#endif