#pragma once

#include <SDL3/SDL.h>

#define PLATFORM_HAS_KEYBOARD
#define PLATFORM_HAS_MOUSE
#define PLATFORM_HAS_RIGHT_JOY
#define PLATFORM_HAS_TRIGGERS

#if SDL_PLATFORM_PSP
#undef PLATFORM_HAS_KEYBOARD
#undef PLATFORM_HAS_MOUSE
#undef PLATFORM_HAS_RIGHT_JOY
#undef PLATFORM_HAS_TRIGGERS

#elif SDL_PLATFORM_ANDROID
#define PLATFORM_HAS_TOUCH

#else

#endif